### ISSUE TITLE
feat: 안드로이드 스튜디오 기초세팅 진행

### ISSUE THREAD

**Issue by junseo511** [Team-WSS/WSS-Android#1]
## ⚔️ Kind (Required)    
`FEAT`

## 📜 Overview (Required)    
전반적인 기초세팅을 진행합니다.

> **✔️ To do**    
> - [x] .gitignore 추가
> - [x] gradle 의존성 추가
> - [x] 패키지 분리
> - [x] 화면 회전 잠금
> - [x] 네트워크 모듈 추가
> - [x] 다크모드 잠금
> - [x] 기본 테마 설정
> - [x] 이슈 템플릿 추가
> - [x] PR 템플릿 추가
> - [x] 라벨 추가
> - [x] 도메인 추가
> - [x] color system 구성
> - [x] font system 구성

## 📍 Note (Optional) 
혹시 추가해야 할 사항이 있다면 알려주세요!

**Comment by librarywon** [comment]
의존성 추가
패키지 분리
레트로핏 세팅

**Comment by junseo511** [comment]
@librarywon 패키지 분리 바로 진행하나요?

**Comment by librarywon** [comment]
data, view 정도는 분리해두는 것이 좋겠지요?
