### ISSUE TITLE
feat: 마이페이지 설정 뷰 구현

### ISSUE THREAD

**Issue by yeonjeen** [Team-WSS/WSS-Android#16]
## ⚔️ Kind (Required)   
`feat`

## 📜 Overview (Required)   
환경설정, 계정정보, 비공개여부 구현

> **✔️ To do**   
- [ ] 설정 xml 구현
- [ ] 환경설정 구현
- [ ] 계정정보 구현
- [ ] 비공개여부 구현

## 📍 Note (Optional)

**Comment by m6z1** [comment]
#162 #177 #203 #175 #198 #220 #178 에서 해결하여 이슈 닫음
