### ISSUE TITLE
feat: 작품상세 뷰 구글 권장 아키텍처 및 레포지토리 패턴 적용

### ISSUE THREAD

**Issue by junseo511** [Team-WSS/WSS-Android#71]
## 📜 Overview (Required)    
  
작품상세 뷰 구글 권장 아키텍처 및 레포지토리 패턴 적용

## 📌 Child Issue(Optional)  

No response  

## 📍 Note (Optional) 
No response

**Comment by s9hn** [comment]
어떤 아키텍처이고 어떤 디자인패턴인지 구체적으로 작성바랍니다!
